<?xml version='1.0' encoding='UTF-8' standalone='yes'?>

<!DOCTYPE Workspace
[
    <!ELEMENT Workspace (Value*,Ravel*,SymbolTable,Symbol*,StateIndicator)>
    <!ATTLIST Workspace  wsid     CDATA #REQUIRED>
    <!ATTLIST Workspace  year     CDATA #REQUIRED>
    <!ATTLIST Workspace  month    CDATA #REQUIRED>
    <!ATTLIST Workspace  day      CDATA #REQUIRED>
    <!ATTLIST Workspace  hour     CDATA #REQUIRED>
    <!ATTLIST Workspace  minute   CDATA #REQUIRED>
    <!ATTLIST Workspace  second   CDATA #REQUIRED>
    <!ATTLIST Workspace  timezone CDATA #REQUIRED>

        <!ELEMENT Value (#PCDATA)>
        <!ATTLIST Value flg    CDATA #REQUIRED>
        <!ATTLIST Value vid    CDATA #REQUIRED>
        <!ATTLIST Value parent CDATA #IMPLIED>
        <!ATTLIST Value rk     CDATA #REQUIRED>
        <!ATTLIST Value sh-0   CDATA #IMPLIED>
        <!ATTLIST Value sh-1   CDATA #IMPLIED>
        <!ATTLIST Value sh-2   CDATA #IMPLIED>
        <!ATTLIST Value sh-3   CDATA #IMPLIED>
        <!ATTLIST Value sh-4   CDATA #IMPLIED>
        <!ATTLIST Value sh-5   CDATA #IMPLIED>
        <!ATTLIST Value sh-6   CDATA #IMPLIED>
        <!ATTLIST Value sh-7   CDATA #IMPLIED>

        <!ELEMENT Ravel (#PCDATA)>
        <!ATTLIST Ravel vid    CDATA #REQUIRED>
        <!ATTLIST Ravel cells  CDATA #REQUIRED>

        <!ELEMENT SymbolTable (Symbol*)>
        <!ATTLIST SymbolTable size CDATA #REQUIRED>

            <!ELEMENT Symbol (unused-name|Variable|Function|Label|Shared-Variable)*>
            <!ATTLIST Symbol name       CDATA #REQUIRED>
            <!ATTLIST Symbol stack-size CDATA #REQUIRED>

                <!ELEMENT unused-name EMPTY>

                <!ELEMENT Variable (#PCDATA)>
                <!ATTLIST Variable vid CDATA #REQUIRED>

                <!ELEMENT Function (UCS)>

                <!ELEMENT Label (#PCDATA)>
                <!ATTLIST Label value CDATA #REQUIRED>

                <!ELEMENT Shared-Variable (#PCDATA)>
                <!ATTLIST Shared-Variable key CDATA #REQUIRED>

        <!ELEMENT UCS (#PCDATA)>
        <!ATTLIST UCS uni CDATA #REQUIRED>

        <!ELEMENT StateIndicator (SI-entry*)>
        <!ATTLIST StateIndicator levels CDATA #REQUIRED>

            <!ELEMENT SI-entry ((Execute|Statements|UserFunction),Parser+)>
            <!ATTLIST SI-entry level     CDATA #REQUIRED>
            <!ATTLIST SI-entry pc        CDATA #REQUIRED>
            <!ATTLIST SI-entry line      CDATA #REQUIRED>

                <!ELEMENT Statements (UCS)>

                <!ELEMENT Execute (UCS)>

                <!ELEMENT UserFunction (#PCDATA)>
                <!ATTLIST UserFunction ufun-name       CDATA #REQUIRED>
                <!ATTLIST UserFunction symbol-level    CDATA #REQUIRED>
                <!ATTLIST UserFunction creation-time   CDATA #IMPLIED>
                <!ATTLIST UserFunction exec-properties CDATA #IMPLIED>

                <!ELEMENT Parser (Token*)>
                <!ATTLIST Parser assign-pending CDATA #REQUIRED>
                <!ATTLIST Parser lookahead-high CDATA #REQUIRED>
                    <!ELEMENT Token (#PCDATA)>
                    <!ATTLIST Token pc           CDATA #REQUIRED>
                    <!ATTLIST Token tag          CDATA #REQUIRED>
                    <!ATTLIST Token char         CDATA #IMPLIED>
                    <!ATTLIST Token int          CDATA #IMPLIED>
                    <!ATTLIST Token float        CDATA #IMPLIED>
                    <!ATTLIST Token real         CDATA #IMPLIED>
                    <!ATTLIST Token imag         CDATA #IMPLIED>
                    <!ATTLIST Token sym          CDATA #IMPLIED>
                    <!ATTLIST Token line         CDATA #IMPLIED>
                    <!ATTLIST Token vid          CDATA #IMPLIED>
                    <!ATTLIST Token index        CDATA #IMPLIED>
                    <!ATTLIST Token fun-id       CDATA #IMPLIED>
                    <!ATTLIST Token ufun-name    CDATA #IMPLIED>
                    <!ATTLIST Token symbol-level CDATA #IMPLIED>
                    <!ATTLIST Token comment  CDATA #IMPLIED>

]>


    <!-- hour/minute/second is )SAVE time in UTC (aka. GMT).
         timezone is offset to UTC in seconds.
         local time is UTC + offset -->
<Workspace wsid="acicpas/randomness" year="2016" month="3" day="13"
           hour="16" minute="32" second="18" timezone="28800"
           saving_SVN="9479">

  <Value flg="400" vid="0" parent="-1" rk="0"/>
  <Value flg="400" vid="1" parent="-1" rk="0"/>
  <Value flg="400" vid="2" parent="-1" rk="0"/>
  <Value flg="400" vid="3" parent="-1" rk="0"/>
  <Value flg="400" vid="4" parent="-1" rk="0"/>
  <Value flg="400" vid="5" parent="-1" rk="1" sh-0="0"/>
  <Value flg="400" vid="6" parent="-1" rk="0"/>
  <Value flg="400" vid="7" parent="-1" rk="1" sh-0="6"/>
  <Value flg="400" vid="8" parent="-1" rk="0"/>
  <Value flg="400" vid="9" parent="-1" rk="0"/>
  <Value flg="400" vid="10" parent="-1" rk="0"/>
  <Value flg="400" vid="11" parent="-1" rk="0"/>
  <Value flg="400" vid="12" parent="-1" rk="0"/>
  <Value flg="400" vid="13" parent="-1" rk="0"/>
  <Value flg="400" vid="14" parent="-1" rk="0"/>
  <Value flg="400" vid="15" parent="-1" rk="0"/>
  <Value flg="400" vid="16" parent="-1" rk="0"/>
  <Value flg="400" vid="17" parent="-1" rk="0"/>
  <Value flg="400" vid="18" parent="-1" rk="0"/>
  <Value flg="400" vid="19" parent="-1" rk="0"/>
  <Value flg="400" vid="20" parent="-1" rk="0"/>
  <Value flg="400" vid="21" parent="-1" rk="0"/>
  <Value flg="400" vid="22" parent="-1" rk="0"/>
  <Value flg="400" vid="23" parent="-1" rk="0"/>
  <Value flg="400" vid="24" parent="-1" rk="0"/>
  <Value flg="400" vid="25" parent="-1" rk="0"/>
  <Value flg="400" vid="26" parent="-1" rk="0"/>
  <Value flg="400" vid="27" parent="-1" rk="0"/>
  <Value flg="400" vid="28" parent="-1" rk="0"/>
  <Value flg="400" vid="29" parent="-1" rk="0"/>
  <Value flg="400" vid="30" parent="-1" rk="0"/>
  <Value flg="400" vid="31" parent="-1" rk="0"/>
  <Value flg="400" vid="32" parent="-1" rk="0"/>
  <Value flg="400" vid="33" parent="-1" rk="0"/>
  <Value flg="400" vid="34" parent="-1" rk="0"/>
  <Value flg="400" vid="35" parent="-1" rk="0"/>
  <Value flg="400" vid="36" parent="-1" rk="0"/>
  <Value flg="400" vid="37" parent="-1" rk="0"/>
  <Value flg="400" vid="38" parent="-1" rk="0"/>
  <Value flg="400" vid="39" parent="-1" rk="0"/>
  <Value flg="400" vid="40" parent="-1" rk="0"/>
  <Value flg="400" vid="41" parent="-1" rk="0"/>
  <Value flg="400" vid="42" parent="-1" rk="0"/>
  <Value flg="400" vid="43" parent="-1" rk="0"/>
  <Value flg="400" vid="44" parent="-1" rk="0"/>
  <Value flg="400" vid="45" parent="-1" rk="0"/>
  <Value flg="400" vid="46" parent="-1" rk="0"/>
  <Value flg="400" vid="47" parent="-1" rk="0"/>
  <Value flg="400" vid="48" parent="-1" rk="0"/>
  <Value flg="400" vid="49" parent="-1" rk="0"/>
  <Value flg="400" vid="50" parent="-1" rk="0"/>
  <Value flg="400" vid="51" parent="-1" rk="0"/>
  <Value flg="400" vid="52" parent="-1" rk="0"/>
  <Value flg="400" vid="53" parent="-1" rk="0"/>
  <Value flg="400" vid="54" parent="-1" rk="0"/>
  <Value flg="400" vid="55" parent="-1" rk="0"/>
  <Value flg="400" vid="56" parent="-1" rk="0"/>
  <Value flg="400" vid="57" parent="-1" rk="0"/>
  <Value flg="400" vid="58" parent="-1" rk="0"/>
  <Value flg="400" vid="59" parent="-1" rk="1" sh-0="3"/>
  <Value flg="400" vid="60" parent="-1" rk="0"/>
  <Value flg="400" vid="61" parent="-1" rk="0"/>
  <Value flg="400" vid="62" parent="-1" rk="1" sh-0="256"/>
  <Value flg="400" vid="63" parent="-1" rk="1" sh-0="4"/>
  <Value flg="400" vid="64" parent="-1" rk="1" sh-0="21"/>
  <Ravel vid="0" cells="³16807"/>
  <Ravel vid="1" cells="³80"/>
  <Ravel vid="2" cells="³0"/>
  <Ravel vid="3" cells="² ⁰"/>
  <Ravel vid="4" cells="³10"/>
  <Ravel vid="5" cells="² ⁰"/>
  <Ravel vid="6" cells="³1"/>
  <Ravel vid="7" cells="².,⁰¹22C6²0_⁰¹AF"/>
  <Ravel vid="8" cells="⁴1e-13"/>
  <Ravel vid="9" cells="²a⁰"/>
  <Ravel vid="10" cells="³0"/>
  <Ravel vid="11" cells="³1"/>
  <Ravel vid="12" cells="³0"/>
  <Ravel vid="13" cells="³0"/>
  <Ravel vid="14" cells="³0"/>
  <Ravel vid="15" cells="³1"/>
  <Ravel vid="16" cells="³0"/>
  <Ravel vid="17" cells="³0"/>
  <Ravel vid="18" cells="³0"/>
  <Ravel vid="19" cells="³0"/>
  <Ravel vid="20" cells="³3"/>
  <Ravel vid="21" cells="⁴0.5"/>
  <Ravel vid="22" cells="³4"/>
  <Ravel vid="23" cells="⁴0.5"/>
  <Ravel vid="24" cells="³1"/>
  <Ravel vid="25" cells="³0"/>
  <Ravel vid="26" cells="³1"/>
  <Ravel vid="27" cells="³2"/>
  <Ravel vid="28" cells="³2"/>
  <Ravel vid="29" cells="³2"/>
  <Ravel vid="30" cells="³0"/>
  <Ravel vid="31" cells="³3"/>
  <Ravel vid="32" cells="³2"/>
  <Ravel vid="33" cells="³0"/>
  <Ravel vid="34" cells="³2"/>
  <Ravel vid="35" cells="³3"/>
  <Ravel vid="36" cells="³0"/>
  <Ravel vid="37" cells="³0"/>
  <Ravel vid="38" cells="³1"/>
  <Ravel vid="39" cells="³1"/>
  <Ravel vid="40" cells="³3"/>
  <Ravel vid="41" cells="³2"/>
  <Ravel vid="42" cells="³3"/>
  <Ravel vid="43" cells="³2"/>
  <Ravel vid="44" cells="³3"/>
  <Ravel vid="45" cells="³1"/>
  <Ravel vid="46" cells="³3"/>
  <Ravel vid="47" cells="³1"/>
  <Ravel vid="48" cells="³0"/>
  <Ravel vid="49" cells="³1"/>
  <Ravel vid="50" cells="³1"/>
  <Ravel vid="51" cells="³0"/>
  <Ravel vid="52" cells="³8"/>
  <Ravel vid="53" cells="³0"/>
  <Ravel vid="54" cells="³0"/>
  <Ravel vid="55" cells="³0"/>
  <Ravel vid="56" cells="³0"/>
  <Ravel vid="57" cells="³1"/>
  <Ravel vid="58" cells="³0"/>
  <Ravel vid="59" cells="¹8¹D¹A
    "/>
  <Ravel vid="60" cells="³0"/>
  <Ravel vid="61" cells="³0"/>
  <Ravel vid="62" cells="¹0¹1¹2¹3¹4¹5¹6¹7¹8¹9¹A
    ¹B¹C¹D¹E¹F¹10¹11¹12¹13¹14¹15¹16¹17¹18¹19¹1A¹1B¹1C¹1D¹1E¹1F² !⁰¹22²#$⁰
    ²%⁰¹26²'()*+,-./0123456789:;⁰¹3C²=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_⁰
    ²`abcdefghijklmnopqrstuvwxyz{|}~⁰¹7F¹A5¹20AC¹21C4¹2227¹223C¹226C
    ¹22C6¹22F8¹2338¹233A¹233C¹233E¹2341¹A1¹2363¹2345¹2395¹235E¹2339¹2346
    ¹2364¹2347¹2348¹234A¹22A4¹3BB¹234D¹234F¹A3¹22A5¹2376¹2336¹2350¹2351
    ¹3C7¹2262¹2356¹2357¹2358¹235A¹235B¹2308¹235C¹2362¹222A¹2368¹2355
    ¹234E¹236C¹236A¹2223¹2502¹2524¹235F¹2206¹2207¹2192¹2563¹2551¹2557
    ¹255D¹2190¹230A¹2510¹2514¹2534¹252C¹251C¹2500¹253C¹2191¹2193¹2554
    ¹255A¹2569¹2566¹2560¹2550¹256C¹2261¹2378¹2377¹2235¹2337¹2342¹233B
    ¹22A2¹22A3¹25CA¹2518¹250C¹2588¹2584¹258C¹2590¹2580¹237A¹2379¹2282
    ¹2283¹235D¹2372¹2374¹2371¹233D¹2296¹25CB¹2228¹2373¹2349¹2208¹2229
    ¹233F¹2340¹2265¹2264¹2260¹D7¹F7¹2359¹2218¹2375¹236B¹234B¹2352¹AF¹A8
    ¹A0"/>
  <Ravel vid="63" cells="³-1³0³0³0"/>
  <Ravel vid="64" cells="²SystemVariable.cc:675⁰"/>
  <SymbolTable size="38">
    <Symbol name="Nv" stack-size="1">
      <Function creation-time="1457877530639458" exec-properties="0,0,0,0">
        <UCS uni="²r ⁰¹2190² p Nv x ;m;v;a;b⁰¹A
          ²m ⁰¹2190² ⁰¹2191²p⁰¹A
          ²v ⁰¹2190² ⁰¹2191²1⁰¹2193²p⁰¹A
          ²a ⁰¹2190² (v - 1) ⁰¹F7² m⁰¹A
          ²b ⁰¹2190² v ⁰¹F7² m⁰¹A
          ²r ⁰¹2190² +/ (a ⁰¹3C² x) ⁰¹2227² (x ⁰¹3C² b)⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="R" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="a" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="addfac" stack-size="1">
      <Function creation-time="1457877530639518" exec-properties="0,0,0,0">
        <UCS uni="²y ⁰¹2190² a addfac x⁰¹A
          ²y ⁰¹2190² fact a + x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="avg" stack-size="1">
      <Function creation-time="1457877530639539" exec-properties="0,0,0,0">
        <UCS uni="²R ⁰¹2190² avg x⁰¹A
          ²R ⁰¹2190² (+/ x) ⁰¹F7² ⁰¹2374² x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="b" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="chaotic" stack-size="1">
      <Function creation-time="1457880100244348" exec-properties="0,0,0,0">
        <UCS uni="²y ⁰¹2190²  chaotic x⁰¹A
          ¹2192² ((x ⁰¹2265² 0) ⁰¹2227² (x ⁰¹2264² 1 ⁰¹F7² 3)) / p⁰¹A
          ¹2192² ((x ⁰¹2265² 1 ⁰¹F7² 3) ⁰¹2227² (x ⁰¹2264² 2 ⁰¹F7² 3)) /⁰
          ² q⁰¹A
          ¹2192² ((x ⁰¹2265² 2 ⁰¹F7² 3) ⁰¹2227² ( x ⁰¹2264² 1)) / r⁰¹A
          ¹2192²  ((x > 1) ⁰¹2228² (x ⁰¹3C² 0)) / 0⁰¹A
          ²r: y ⁰¹2190² (3 ⁰¹D7² x) - 2⁰¹A
          ¹2192² 0⁰¹A
          ²q: y ⁰¹2190² 2 - 3 ⁰¹D7² x⁰¹A
          ¹2192² 0⁰¹A
          ²p: y ⁰¹2190² 2 ⁰¹D7² x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="chatic" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="doublefac" stack-size="1">
      <Function creation-time="1457877530639579" exec-properties="0,0,0,0">
        <UCS uni="²y ⁰¹2190² doublefac x⁰¹A
          ²y ⁰¹2190² 2 multifac x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="equidistr" stack-size="1">
      <Function creation-time="1457885247082601" exec-properties="0,0,0,0">
        <UCS uni="²v ⁰¹2190² a equidistr n⁰¹A
          ¹235D² 3.1415926 equidistr 1000⁰¹A
          ²v ⁰¹2190² fact ⁰¹A8² (a ⁰¹D7² ⁰¹2373²n)⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="ev" stack-size="1">
      <Function creation-time="1457877530639614" exec-properties="0,0,0,0">
        <UCS uni="²r ⁰¹2190² ev x ;var;sum⁰¹A
          ²var ⁰¹2190² (x - avg x) * 2⁰¹A
          ²sum ⁰¹2190² +/ var⁰¹A
          ²r ⁰¹2190² sum ⁰¹F7² ⁰¹2374² x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="fact" stack-size="1">
      <Function creation-time="1457877530639648" exec-properties="0,0,0,0">
        <UCS uni="²n ⁰¹2190² fact x⁰¹A
          ¹235D² the factorial part of x⁰¹A
          ²n ⁰¹2190² x - ⁰¹230A²x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="firstseries" stack-size="1">
      <Function creation-time="1457877530639710" exec-properties="0,0,0,0">
        <UCS uni="²v ⁰¹2190² n firstseries x ; i⁰¹A
          ²i ⁰¹2190² 1⁰¹A
          ²v ⁰¹2190² ,x⁰¹A
          ²h: ⁰¹2192² (i = n) / 0⁰¹A
          ²i ⁰¹2190² i + 1⁰¹A
          ²x ⁰¹2190² 0.5 + 4 ⁰¹D7² (x - 0.5) * 3⁰¹A
          ²v ⁰¹2190² v,x⁰¹A
          ¹2192² h⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="fract" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="h" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="i" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="m" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="multifac" stack-size="1">
      <Function creation-time="1457877530639765" exec-properties="0,0,0,0">
        <UCS uni="²y ⁰¹2190² m multifac x⁰¹A
          ²y ⁰¹2190² fact m ⁰¹D7² x⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="myfact" stack-size="1">
      <Function creation-time="1457877530639820" exec-properties="0,0,0,0">
        <UCS uni="¹3BB¹2190¹237A² myfact ⁰¹2375¹A
          ¹3BB¹2190²fact (⁰¹237A² + ⁰¹2375²)⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="n" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="op" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="p" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="q" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="r" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="randomseries" stack-size="1">
      <Function creation-time="1457877530639888" exec-properties="0,0,0,0">
        <UCS uni="²v ⁰¹2190² n randomseries a ; x1 ; i⁰¹A
          ²x1 ⁰¹2190² 0⁰¹A
          ²i ⁰¹2190² 0⁰¹A
          ²v ⁰¹2190² ⁰¹2373²0⁰¹A
          ²h: ⁰¹2192² (i = n) / 0⁰¹A
          ²i ⁰¹2190² i + 1⁰¹A
          ²x1 ⁰¹2190² fact x1 + a⁰¹A
          ²v ⁰¹2190² v,x1⁰¹A
          ¹2192² h⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="seriesgen" stack-size="1">
      <Function creation-time="1457880555686335" exec-properties="0,0,0,0">
        <UCS uni="²v ⁰¹2190² a (op seriesgen n) x1 ; i⁰¹A
          ¹235D² (doublefac seriesgen 100) 0.02675⁰¹A
          ¹235D² 3 (multifac seriesgen 100) 0.09876⁰¹A
          ¹235D² 5.634 (addfac seriesgen 100) 0.0283472⁰¹A
          ¹235D² (chaotic seriesgen 100) 0.098765⁰¹A
          ²i ⁰¹2190² 0⁰¹A
          ²v ⁰¹2190² ⁰¹2373²0⁰¹A
          ²h: ⁰¹2192² (i = n) / 0⁰¹A
          ²i ⁰¹2190² i + 1⁰¹A
          ¹2192² (0 = ⁰¹2395²NC 'a') / p⁰¹A
          ²x1 ⁰¹2190² a op x1⁰¹A
          ¹2192² q⁰¹A
          ²p: x1 ⁰¹2190² op x1⁰¹A
          ²q: v ⁰¹2190² v,x1⁰¹A
          ¹2192² h⁰¹A
          "/>
      </Function>
    </Symbol>

    <Symbol name="sum" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="v" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="var" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="x" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="x1" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="y" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="λ" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="χ" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="⍵" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="⍶" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="⍹" stack-size="1">
      <unused-name/>
    </Symbol>

    <Symbol name="⍺" stack-size="1">
      <unused-name/>
    </Symbol>

  </SymbolTable>

  <Symbol name="⎕AI" stack-size="1">
    <Variable vid="63"/>
  </Symbol>

  <Symbol name="⎕ARG" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕AV" stack-size="1">
    <Variable vid="62"/>
  </Symbol>

  <Symbol name="⎕CT" stack-size="1">
    <Variable vid="8"/>
  </Symbol>

  <Symbol name="⎕EM" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕ET" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⎕FC" stack-size="1">
    <Variable vid="7"/>
  </Symbol>

  <Symbol name="⎕IO" stack-size="1">
    <Variable vid="6"/>
  </Symbol>

  <Symbol name="⎕L" stack-size="1">
    <Variable vid="55"/>
  </Symbol>

  <Symbol name="⎕LC" stack-size="1">
    <Variable vid="61"/>
  </Symbol>

  <Symbol name="⎕LX" stack-size="1">
    <Variable vid="5"/>
  </Symbol>

  <Symbol name="⎕PP" stack-size="1">
    <Variable vid="4"/>
  </Symbol>

  <Symbol name="⎕PR" stack-size="1">
    <Variable vid="3"/>
  </Symbol>

  <Symbol name="⎕PS" stack-size="1">
    <Variable vid="2"/>
  </Symbol>

  <Symbol name="⎕PW" stack-size="1">
    <Variable vid="1"/>
  </Symbol>

  <Symbol name="⎕R" stack-size="1">
    <Variable vid="54"/>
  </Symbol>

  <Symbol name="⎕RL" stack-size="1">
    <Variable vid="0"/>
  </Symbol>

  <Symbol name="⎕SVE" stack-size="1">
    <Variable vid="60"/>
  </Symbol>

  <Symbol name="⎕SYL" stack-size="1">
    <Variable vid="53"/>
  </Symbol>

  <Symbol name="⎕TC" stack-size="1">
    <Variable vid="59"/>
  </Symbol>

  <Symbol name="⎕TS" stack-size="1">
    <Variable vid="58"/>
  </Symbol>

  <Symbol name="⎕TZ" stack-size="1">
    <Variable vid="52"/>
  </Symbol>

  <Symbol name="⎕UL" stack-size="1">
    <Variable vid="57"/>
  </Symbol>

  <Symbol name="⎕X" stack-size="1">
    <Variable vid="51"/>
  </Symbol>

  <Symbol name="⎕WA" stack-size="1">
    <Variable vid="56"/>
  </Symbol>

  <Symbol name="λ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍺" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍵" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="χ" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍶" stack-size="1">
    <unused-name/>
  </Symbol>

  <Symbol name="⍹" stack-size="1">
    <unused-name/>
  </Symbol>

  <StateIndicator levels="0">
  </StateIndicator>

</Workspace>
    
